name: Without marketplace - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: docker install or not
        run: docker --version

      - name: docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 

      - name: build docker Img 
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/without_market_doc-img:latest .
      - name: View the Docker Img
        run: |
          docker images
      - name: push docker img
        run: |

          docker push ${{ secrets.DOCKER_USERNAME }}/without_market_doc-img:latest




