name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Check Docker version
      - name: Check Docker version
        run: docker --version

      # Step 3: Docker login manually
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  

      # Step 4: Build Docker image locally
      - name: Build Docker image
        run: |
          docker build -t without_market_doc-img:latest .

      # Step 5: Tag image for Docker Hub
      - name: Tag Docker image
        run: |
          docker tag without_market_doc-img:latest ${{ secrets.DOCKER_USERNAME }}/without_market_doc-img:latest

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/without_market_doc-img:latest

      # Step 7: Verify pushed image
      - name: View Docker images
        run: docker images
